In [26]:
import pickle

In [27]:
X = pickle.load(open('X.pkl', 'rb'))
y = pickle.load(open('y.pkl', 'rb'))

In [28]:
X

array([[[ 60,  52,  63, ..., 100,  99, 100],
        [ 67,  67,  63, ...,  93,  92,  96],
        [ 72,  76,  63, ...,  96,  99,  95],
        ...,
        [105, 116, 122, ...,  84,  86,  87],
        [115, 125, 131, ...,  83,  85,  85],
        [130, 130, 134, ...,  85,  85,  89]],

       [[ 44,  23,  24, ...,  70,  80,  63],
        [ 30,  31,  26, ...,  75,  80,  79],
        [ 24,  29,  25, ...,  81,  81,  80],
        ...,
        [ 43,  61,  38, ...,  25,  25,  42],
        [ 47,  56,  49, ...,  31,  43,  82],
        [ 42,  49,  41, ...,  58,  97,  87]],

       [[ 57,  45,  37, ...,  58,  71,  74],
        [ 49,  49,  42, ...,  63,  59,  67],
        [ 49,  42,  49, ...,  67,  56,  54],
        ...,
        [ 39,  34,  37, ...,  41,  40,  37],
        [ 33,  30,  36, ...,  43,  40,  38],
        [ 34,  30,  33, ...,  46,  42,  42]],

       ...,

       [[ 38,  38,  37, ...,  38,  37,  38],
        [ 40,  38,  37, ...,  37,  37,  38],
        [ 39,  39,  38, ...,  37,  38,  41

In [29]:
y

array([1, 1, 1, ..., 0, 0, 1])

In [30]:
X = X/255   #Feature scaling.. lesser the value easier the computation

In [31]:
X.shape

(1150, 120, 120)

In [32]:
X

array([[[0.23529412, 0.20392157, 0.24705882, ..., 0.39215686,
         0.38823529, 0.39215686],
        [0.2627451 , 0.2627451 , 0.24705882, ..., 0.36470588,
         0.36078431, 0.37647059],
        [0.28235294, 0.29803922, 0.24705882, ..., 0.37647059,
         0.38823529, 0.37254902],
        ...,
        [0.41176471, 0.45490196, 0.47843137, ..., 0.32941176,
         0.3372549 , 0.34117647],
        [0.45098039, 0.49019608, 0.51372549, ..., 0.3254902 ,
         0.33333333, 0.33333333],
        [0.50980392, 0.50980392, 0.5254902 , ..., 0.33333333,
         0.33333333, 0.34901961]],

       [[0.17254902, 0.09019608, 0.09411765, ..., 0.2745098 ,
         0.31372549, 0.24705882],
        [0.11764706, 0.12156863, 0.10196078, ..., 0.29411765,
         0.31372549, 0.30980392],
        [0.09411765, 0.11372549, 0.09803922, ..., 0.31764706,
         0.31764706, 0.31372549],
        ...,
        [0.16862745, 0.23921569, 0.14901961, ..., 0.09803922,
         0.09803922, 0.16470588],
        [0.1

In [34]:
X = X.reshape(-1, 120, 120, 1)

In [35]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten

In [36]:
model = Sequential()

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Conv2D(64, (3,3), activation = 'relu'))
model.add(MaxPooling2D((2,2)))

model.add(Flatten())

model.add(Dense(128, input_shape = X.shape[1:], activation = 'relu'))

model.add(Dense(2, activation = 'softmax'))

In [37]:
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [38]:
model.fit(X, y, epochs=5, validation_split=0.1)

Epoch 1/5
33/33 [==============================] - 32s 862ms/step - loss: 0.6678 - accuracy: 0.6918 - val_loss: 0.5316 - val_accuracy: 0.7478
Epoch 2/5
33/33 [==============================] - 28s 831ms/step - loss: 0.5225 - accuracy: 0.7556 - val_loss: 0.6394 - val_accuracy: 0.6957
Epoch 3/5
33/33 [==============================] - 27s 827ms/step - loss: 0.4674 - accuracy: 0.7923 - val_loss: 0.4895 - val_accuracy: 0.7826
Epoch 4/5
33/33 [==============================] - 27s 829ms/step - loss: 0.3312 - accuracy: 0.8580 - val_loss: 0.4540 - val_accuracy: 0.8261
Epoch 5/5
33/33 [==============================] - 28s 847ms/step - loss: 0.2420 - accuracy: 0.9005 - val_loss: 0.4495 - val_accuracy: 0.8348


In [39]:
X.shape

(1150, 120, 120, 1)

In [40]:
import time

time.time()

1677663328.6834123